export const environment = {
  production: true,
  PAYPAL_CLIENT_ID: 'EMRO_PAYPAL_CLIENT_ID',
  GOOGLE_MAP_KEY: 'EMRO_GOOGLE_MAP_KEY',
  WEATHER_API: 'EMRO_WEATHER_API',
  WEATHER_API_KEY: 'EMRO_WEATHER_API_KEY',
  UUID: "00000000-0000-0000-0000-000000000000",
  SELLER_ID: 'EMRO_SELLER_ID',
  BASE_URL: 'EMRO_BASE_URL',
  HOST_URL: 'EMRO_HOST_URL',
  SIGNAL_R_URL: 'EMRO_SIGNAL_R_URL',
};
