apiVersion: v1
kind: Service
metadata:
  name: {{.Values.portal.name }}
spec:
  selector:
    app: {{.Values.portal.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.portal.image.targetPort }}
      nodePort: {{.Values.portal.image.nodePort }}
  type: {{.Values.portal.service.type }}
