apiVersion: v1
kind: Service
metadata:
  name: {{.Values.postgresql.name }}
spec:
  selector:
    app: {{.Values.postgresql.name }}
  ports:
    - name: {{.Values.postgresql.name }}
      port: 5432
      targetPort: {{.Values.postgresql.image.targetPort }}
      nodePort: {{.Values.postgresql.image.nodePort }}
  type: {{.Values.postgresql.service.type }}

