CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-12', 'IDLW', 'International Date Line West');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-11', 'SST', 'Samoa Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-10', 'HST', 'Hawaii Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-9:30', 'MART', 'Marquesas Islands Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-9', 'AKST', 'Alaska Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-8', 'PST', 'Pacific Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-8', 'AKDT', 'Alaska Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-7', 'MST', 'Mountain Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-7', 'PDT', 'Pacific Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-6', 'CST', 'Central Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-6', 'MDT', 'Mountain Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-5', 'EST', 'Eastern Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-5', 'CDT', 'Central Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-4', 'AST', 'Atlantic Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-4', 'EDT', 'Eastern Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-3:30', 'NST', 'Newfoundland Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-3', 'ART', 'Argentina Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-3', 'ADT', 'Atlantic Daylight time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-2:30', 'NDT', 'Newfoundland Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-2', 'GST', 'South Georgia Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-2', 'WGST', 'Western Greenland Summer Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC-1', 'EGT', 'Eastern Greenland Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+0', 'GMT', 'Greenwich Mean Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+1', 'CET', 'Central European Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+2', 'EET', 'Eastern European Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+2', 'CEST', 'Central European Summer Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+3', 'MSK', 'Moscow Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+3', 'EEST', 'Eastern European Summer Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+3:30', 'IRST', 'Iran Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+4', 'AMT', 'Gulf Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+4:30', 'AFT', 'Afghanistan Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+4:30', 'IRDT', 'Iran Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+5', 'PKT', 'Pakistan Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+5:30', 'IST', 'India Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+6', 'OMSK', 'Omsk Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+6:30', 'MMT', 'Myanmar Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+7', 'ICT', 'Indochina Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+8', 'CST', 'China Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+9', 'JST', 'Japan Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+9:30', 'ACT', 'Australia Central Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+10', 'AEST', 'Australian Eastern Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+10:30', 'LHST', 'Lord Howe Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+10:30', 'ACDT', 'Australian Central Daylight Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+11', 'SAKT', 'Sakhalin Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+11', 'AEST', 'Australian Eastern Daylight Savings Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+12', 'NZST', 'New Zealand Standard Time');
INSERT INTO public."TimeZones"("TimeZoneId", "UTCOffset", "Abbr", "Description") VALUES ( uuid_generate_v4(),'UTC+13', 'NZDT', 'New Zealand Daylight Time');
	
	

