INSERT INTO public."SpecialtyMasters"("SpecialtyId", "SpecialtyName", "CreatedOn")VALUES (uuid_generate_v4(), 'Radiation Oncologist',Current_Timestamp);
INSERT INTO public."SpecialtyMasters"("SpecialtyId", "SpecialtyName", "CreatedOn")VALUES (uuid_generate_v4(), 'Medical Oncologist',Current_Timestamp);
INSERT INTO public."SpecialtyMasters"("SpecialtyId", "SpecialtyName", "CreatedOn")VALUES (uuid_generate_v4(), 'Surgical Oncologist',Current_Timestamp);
INSERT INTO public."SpecialtyMasters"("SpecialtyId", "SpecialtyName", "CreatedOn")VALUES (uuid_generate_v4(), 'Pathologist',Current_Timestamp);
INSERT INTO public."SpecialtyMasters"("SpecialtyId", "SpecialtyName", "CreatedOn")VALUES (uuid_generate_v4(), 'Radiologist',Current_Timestamp);
INSERT INTO public."SpecialtyMasters"("SpecialtyId", "SpecialtyName", "CreatedOn")VALUES (uuid_generate_v4(), 'Interventional Radiologist',Current_Timestamp);
INSERT INTO public."SpecialtyMasters"("SpecialtyId", "SpecialtyName", "CreatedOn")VALUES (uuid_generate_v4(), 'Pediatric Oncologist',Current_Timestamp);

INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Breast',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Ocular',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Gastrointestinal (GI)',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Liver',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Colon',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Genito-uro',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Head and Neck',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Dermatological',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Nephro',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Thoracic',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Gynecologic',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Neuro',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Hemato',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Bone & Musculoskeletal',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Molecular',Current_Timestamp);
INSERT INTO public."SubSpecialtyMasters"("SubSpecialityId", "SubSpecialityName", "CreatedOn")VALUES (uuid_generate_v4(), 'Other',Current_Timestamp);